Make all unit tests required, but allow skipped checks

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,6 +51,7 @@ jobs:
               - 'var/**'
               - 'README.rst'
               - 'tags.yaml'
+              - 'pyproject.toml'
             style:
               - '.github/**'
               - 'bin/**'
@@ -61,6 +62,8 @@ jobs:
               - 'repo/**'
               - 'systems/**'
               - 'var/**'
+              - 'pyproject.toml'
+              - '.flake8'
             run:
               - '.github/**'
               - 'bin/**'
@@ -82,6 +85,7 @@ jobs:
               - 'repo/**'
               - 'systems/**'
               - 'var/**'
+              - 'pyproject.toml'
             license:
               - '.github/**'
               - 'bin/**'
@@ -122,3 +126,23 @@ jobs:
     if: ${{ needs.changes.outputs.license == 'true' }}
     needs: changes
     uses: ./.github/workflows/license.yml
+
+  all:
+    needs:
+      - changes
+      - docs
+      - style
+      - run
+      - coverage
+      - license
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+    - name: Status summary
+      run: |
+        if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+          echo "One or more required jobs failed or were cancelled"
+          exit 1
+        else
+          echo "All jobs completed successfully"
+        fi
